services:
  server:
    image: ghcr.io/qingquan-li/csv-visualization-server:dev
    ports:
      - "8010:3000"
    restart: always

  client:
    image: ghcr.io/qingquan-li/csv-visualization-client:dev
    ports:
      - "8011:80"
    restart: always
